const WORDS = {
    english: [
        "the","be","to","of","and","a","in","that","have","i","it","for","not","on","with","he","as","you",
        "do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my","one",
        "all","would","there","their","what","so","up","out","if","about","who","get","which","go","me",
        "when","make","can","like","time","no","just","him","know","take","people","into","year","your",
        "good","some","could","them","see","other","than","then","now","look","only","come","its","over",
        "think","also","back","after","use","two","how","our","work","first","well","way","even","new",
        "want","because","any","these","give","day","most","us","great","between","need","large","often",
        "hand","high","place","hold","free","real","life","few","north","open","seem","together","next",
        "white","children","begin","got","walk","example","ease","paper","group","always","music","those",
        "both","mark","book","letter","until","mile","river","car","feet","care","second","enough","plain",
        "girl","usual","young","ready","above","ever","red","list","though","feel","talk","bird","soon",
        "body","dog","family","direct","pose","leave","song","measure","door","product","black","short",
        "numeral","class","wind","question","happen","complete","ship","area","half","rock","order","fire",
        "south","problem","piece","told","knew","pass","since","top","whole","king","space","heard","best",
        "hour","better","true","during","hundred","five","remember","step","early","hold","west","ground",
        "interest","reach","fast","verb","sing","listen","six","table","travel","less","morning","ten",
        "simple","several","vowel","toward","war","lay","against","pattern","slow","center","love","person",
        "money","serve","appear","road","map","rain","rule","govern","pull","cold","notice","voice","unit",
        "power","town","fine","certain","fly","fall","lead","cry","dark","machine","note","wait","plan",
        "figure","star","box","noun","field","rest","correct","able","pound","done","beauty","drive",
        "stood","contain","front","teach","week","final","gave","green","oh","quick","develop","ocean",
        "warm","method","race","language","among","never","finish","general","possible","heart","mind",
        "along","might","close","light","thought","head","under","story","saw","left","late","run",
        "while","press","night","point","city","live","world","still","went","school","should","room",
        "small","end","put","home","read","hand","port","spell","add","move","turn","here","must","big",
        "act","learn","point","state","house","help","old","different","play","found","study","still",
        "last","right","each","tell","does","set","three","air","same","mean","keep","let","begin","seem",
        "earth","eye","never","last","own","say","show","try","much","before","line","right","too","mean",
        "old","any","same","tell","boy","follow","came","want","show","also","around","form","three",
        "small","set","put","end","does","another","well","large","must","big","even","such","here",
        "why","ask","went","men","read","need","land","different","home","us","move","try","kind","hand",
        "picture","again","change","off","play","spell","air","away","animal","house","point","page",
        "letter","mother","answer","found","study","still","learn","should","world","high","every","near",
        "add","food","between","own","below","country","plant","last","school","father","keep","tree",
        "never","start","city","earth","eye","light","thought","head","under","story","saw","far","sea",
        "draw","left","late","run","while","press","close","night","real","life","few","north","open",
        "seem","together","next","white","children","begin","got","walk","example","ease","paper","group",
        "always","music","those","both","mark","book","letter","until","mile","river","car","feet","care"
    ],
    russian: [
        "и","в","не","на","я","что","он","с","это","как","а","по","но","она","к","из","мы","за","вы",
        "так","же","от","все","то","его","да","бы","ты","для","нет","ещё","был","уже","вот","если","ну",
        "мне","тут","где","есть","надо","ней","было","тебя","них","будет","сам","чем","там","потом",
        "себя","ничего","ему","сказал","когда","очень","вас","нас","может","они","тогда","какой","после",
        "через","раз","два","много","хорошо","больше","тоже","время","знаю","свой","только","между",
        "жизнь","под","будто","чтобы","один","сейчас","лучше","такой","человек","сделать","можно","рука",
        "какая","перед","день","здесь","должен","при","даже","быть","того","чуть","были","такие","стал",
        "друг","дело","говорит","слово","место","почему","лицо","ведь","хотя","каждый","стоит","нужно",
        "дом","голова","работа","земля","конец","часть","глаз","город","дверь","думать","ночь","стол",
        "ребёнок","видеть","сила","отец","женщина","машина","случай","ответ","нога","играть","власть",
        "война","наш","море","против","отношение","действие","второй","история","голос","вода","маленький",
        "старый","новый","жить","иметь","взять","понять","последний","стоять","идти","великий","помнить",
        "начать","вопрос","общий","дорога","далёкий","близкий","белый","ждать","давать","утро","некоторый",
        "считать","писать","комната","мать","общество","страна","мир","точно","оставить","ходить","любить",
        "книга","просто","часто","число","путь","главный","сторона","муж","движение","порядок","ответить",
        "тихо","знать","право","система","состояние","область","появиться","сердце","класс","центр",
        "решить","образ","искать","полный","горячий","длинный","молодой","красный","важный","чёрный"
    ],
    code_js: [
        "const","let","var","function","return","if","else","for","while","do","switch","case","break",
        "continue","new","this","class","extends","super","import","export","default","from","async",
        "await","try","catch","finally","throw","typeof","instanceof","void","delete","in","of",
        "true","false","null","undefined","NaN","Infinity","console.log","document","window","Array",
        "Object","String","Number","Boolean","Map","Set","Promise","fetch","JSON.parse","JSON.stringify",
        "addEventListener","querySelector","getElementById","createElement","appendChild","innerHTML",
        "setTimeout","setInterval","clearTimeout","Math.random","Math.floor","Math.ceil","Array.from",
        "Object.keys","Object.values","Object.entries","Array.isArray","Promise.all","Promise.resolve",
        "=","===","!==","=>","...","&&","||","??","?.","++","--","+=","-=","*=","/=",
        "push","pop","shift","unshift","splice","slice","map","filter","reduce","find","forEach",
        "includes","indexOf","join","split","replace","trim","toLowerCase","toUpperCase","toString",
        "length","prototype","constructor","static","get","set","yield","Symbol","Proxy","Reflect",
        "WeakMap","WeakSet","Generator","Iterator","RegExp","Date","Error","TypeError","RangeError"
    ],
    code_py: [
        "def","class","return","if","elif","else","for","while","break","continue","pass","import",
        "from","as","try","except","finally","raise","with","yield","lambda","global","nonlocal",
        "True","False","None","and","or","not","in","is","del","assert","async","await",
        "print","len","range","list","dict","set","tuple","str","int","float","bool","type",
        "input","open","file","read","write","close","append","extend","pop","remove","sort",
        "sorted","reversed","enumerate","zip","map","filter","reduce","any","all","sum","min","max",
        "abs","round","isinstance","issubclass","hasattr","getattr","setattr","delattr","property",
        "staticmethod","classmethod","super","self","__init__","__str__","__repr__","__len__",
        "__getitem__","__setitem__","__delitem__","__iter__","__next__","__enter__","__exit__",
        "ValueError","TypeError","KeyError","IndexError","AttributeError","ImportError","FileNotFoundError",
        "Exception","RuntimeError","StopIteration","os.path","sys.argv","json.loads","json.dumps",
        "re.match","re.search","re.findall","datetime","collections","itertools","functools",
        "=","==","!=",">=","<=","+=","-=","*=","/=","//=","**=","%=","->",":",
        "f\"\"","[]","{}","()","@","#","**","//","%"
    ]
};

const QUOTES = [
    "The only way to do great work is to love what you do.",
    "Innovation distinguishes between a leader and a follower.",
    "Stay hungry, stay foolish.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is what happens when you are busy making other plans.",
    "The purpose of our lives is to be happy.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Never let the fear of striking out keep you from playing the game.",
    "Money and success don't change people; they merely amplify what is already there.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Not how long, but how well you have lived is the main thing.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The way to get started is to quit talking and begin doing.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "Life is really simple, but we insist on making it complicated.",
    "The best time to plant a tree was twenty years ago. The second best time is now.",
    "An unexamined life is not worth living.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "The only impossible journey is the one you never begin.",
    "Act as if what you do makes a difference. It does.",
    "What we achieve inwardly will change outer reality.",
    "The secret of getting ahead is getting started.",
    "Programming is not about typing, it is about thinking.",
    "Code is like humor. When you have to explain it, it is bad.",
    "First, solve the problem. Then, write the code.",
    "Experience is the name everyone gives to their mistakes.",
    "The best error message is the one that never shows up.",
    "Simplicity is the soul of efficiency.",
    "Make it work, make it right, make it fast.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "Talk is cheap. Show me the code.",
    "Programs must be written for people to read, and only incidentally for machines to execute."
];
